// ----- Cliente ---- 
### Adicionar - Serviço ###
POST http://localhost:2000/api/clientes
Content-Type: application/json

{
	"nome": "Nuno Silva",
	"email": "Nsilva@gmail.com",
	"telemovel": "987654333",
	"date": "11/9/2000",
	"nif": "248642998"
}

### Listagem - TUDO ###
GET http://localhost:2000/api/clientes

### Listagem - By ID ###
GET http://localhost:2000/api/clientes/664b22eabc63c671b771598f

### Apagar - By ID ###
DELETE http://localhost:2000/api/clientes/664b22eabc63c671b771598f

### Atualizar - By ID ###
PUT http://localhost:2000/api/clientes/665c487dd3cbd6baf22dbefb
Content-Type: application/json

{
	"nome": "António Marques",
	"email": "Amarques@gmail.com",
	"telemovel": "987654321",
	"date": "7/9/2001",
	"nif": "248642378"
}